### ISSUE TITLE
`make test` fails on Perl 5.10.0

### ISSUE THREAD

**Issue by jdigory** [interchange/interchange#98]
```
server/unixmode.......Can't locate object method "parse" via package "version" at /home/travis/build/jdigory/interchange/build_dir/blib/lib/Vend/Safe.pm line 46.

Compilation failed in require at /home/travis/build/jdigory/interchange/build_dir/blib/lib/Vend/Parse.pm line 29.

BEGIN failed--compilation aborted at /home/travis/build/jdigory/interchange/build_dir/blib/lib/Vend/Parse.pm line 29.

Compilation failed in require at /home/travis/build/jdigory/interchange/build_dir/blib/lib/Vend/Config.pm line 50.

BEGIN failed--compilation aborted at /home/travis/build/jdigory/interchange/build_dir/blib/lib/Vend/Config.pm line 50.

Compilation failed in require at blib/script/interchange line 253.

BEGIN failed--compilation aborted at blib/script/interchange line 253.

not ok 1
```

The full output is here:
https://travis-ci.org/jdigory/interchange/jobs/141144732

It works fine in Perl 5.10.1, so maybe we just close as wontfix?

**Comment by jdigory** [comment]
This may have something to do with 672b8a1

**Comment by jdigory** [comment]
This is resolved now.
